name: Python CI with pytest and pylint

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r pre-requirements.txt
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install freeglut3 freeglut3-dev -y
        sudo apt-get install libxcb-xinerama0 -y
    - name: Test with pytest
      run: |
        pip install pytest
        pip install pytest-cov
        pytest --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html --cov-fail-under=80
#        pytest "src/test_sqlite.py" --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html
#        pytest "tests/test_plot_widget.py" --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html --cov-fail-under=80
    - name: Linting with pylint
      run: |
        pip install pylint
        pylint --rcfile=.pylintrc $(git ls-files '*.py')